### ISSUE TITLE
Parser error on -webkit gradient

### ISSUE THREAD

**Issue by a701440** [google/closure-stylesheets#102]
Appears to fail parsing on this line:

background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0% rgba(0, 0, 0, 0)), color-stop(100% rgba(0, 0, 0, 0.8)));

**Comment by a701440** [comment]
Looks like it gets fixed by adding commas between the color-stop arguments.

**Comment by iflan** [comment]
All examples that I could find on Apple's site have the comma syntax:

https://developer.apple.com/library/content/documentation/InternetWeb/Conceptual/SafariVisualEffectsProgGuide/Gradients/Gradient.html#//apple_ref/doc/uid/TP40008032-CH10-SW1
