### ISSUE TITLE
Parameter source_map_output_level cannot be specified

### ISSUE THREAD

**Issue by rikuayanokozy** [google/closure-stylesheets#12]
Parameter source_map_output_level cannot be specified.
I took a look at [ClosureCommandLineCompiler.java] (https://github.com/google/closure-stylesheets/blob/master/src/com/google/common/css/compiler/commandline/ClosureCommandLineCompiler.java#L132-L136), the following code caused issue:
> @Option(name = "source_map_output_level", usage = "The level to generate "
>         + "source maps. You could choose between DEFAULT, which will generate "
>         + "source map only for selectors, blocks, rules, variables and symbol "
>         + "mappings, and ALL, which outputs mappings for all elements.")
>     private SourceMapDetailLevel sourceMapLevel = SourceMapDetailLevel.DEFAULT;

The Option name does not starts with "--" so we unable to pass it to args4j.

I add double hash before parameter name to fix it: https://github.com/google/closure-stylesheets/pull/13

**Comment by rikuayanokozy** [comment]
https://github.com/google/closure-stylesheets/pull/13

**Comment by iflan** [comment]
Accepted pull request. This should be fixed.
