### ISSUE TITLE
divide is locale sensitive

### ISSUE THREAD

**Issue by twildawnight** [google/closure-stylesheets#14]
The divide function seems locale sensitive.
On a computer with fr_FR as the locale (Windows 7 pro) the compiled CSS for say:

width: divide(BIG_MARGIN, 2);

Where BIG_MARGIN equals "25px" is "12,5px" (a comma). One would expect "12.5px" (a dot)

**Comment by iflan** [comment]
I've found the problem. In [`GssFunctions.java`](https://github.com/google/closure-stylesheets/blob/master/src/com/google/common/css/compiler/gssfunctions/GssFunctions.java#L648), we do:
```java
      String resultString = new DecimalFormat(DECIMAL_FORMAT).format(total);
```
to format the result. Instead, we should do:
```java
      String resultString = new DecimalFormat(DECIMAL_FORMAT, new DecimalFormatSymbols(Locale.US).format(total);
```
I'll see if I can create a patch next week.

**Comment by twildawnight** [comment]
That's a good news. Thanks !

**Comment by iflan** [comment]
This is now fixed.
