### ISSUE TITLE
Add README w/ examples

### ISSUE THREAD

**Issue by dbarnett** [google/closure-stylesheets#19]
The Project Home page at https://code.google.com/p/closure-stylesheets/ had a good summary of Closure Stylesheets' features, but github has no README and doesn't point to any equivalent documentation that I can find. Any reason not to convert the Project Home from code.google.com to a README.md?

**Comment by iflan** [comment]
Porting all of the closure-stylesheets documentation here is one of the things on my TODO list. Since you brought it up, I'll try to get to it this Thursday.

**Comment by iflan** [comment]
Thanks to your prompting, I did this even sooner that I said. You'll find a new [`README.md`](https://github.com/google/closure-stylesheets/blob/master/README.md) on the front page. I also ported the wiki pages from Google Code. I've got a request in with the team to start redirecting the old site here.
