### ISSUE TITLE
Ant build failed - Some input files use or override a deprecated API - Charset issues

### ISSUE THREAD

**Issue by iflan** [google/closure-stylesheets#62]
Originally reported on Google Code with ID 43
```
What steps will reproduce the problem?
1.  Clone closure stylesheets project
2. Run ant 

What is the expected output? What do you see instead?
It should compile and generate the binary

What version of the product are you using? On what operating system?
I'm using it on osX 10.9, Java 1.6.0_65, ant version 1.9.3



```

Reported by `pchillari@google.com` on 2014-04-01 16:52:36

<hr>
 * *Attachment: Screen Shot 2014-04-01 at 5.51.52 PM.png<br>![Screen Shot 2014-04-01 at 5.51.52 PM.png](https://storage.googleapis.com/google-code-attachments/closure-stylesheets/issue-43/comment-0/Screen Shot 2014-04-01 at 5.51.52 PM.png)*

**Comment by iflan** [comment]
@flea89, if I read the issue right, it looks like you're using Java 1.6 and you need to use Java 1.7 to get `java.nio.charsetStandardCharsets`, I believe.

Please re-open if that doesn't work.

**Comment by flea89** [comment]
Thanks, I'll give it a shot again.

**Comment by elhadis** [comment]
what I have to do in this problem
