### ISSUE TITLE
Lack of documentation for @for

### ISSUE THREAD

**Issue by PauloMelo** [google/closure-stylesheets#85]
Hello,
I'm trying to use @for to automatically expand css rules and there are no examples for it. On the other hand there is no example on using the percent either on a @def or @defmixin

`@for $i from 1 to 100 {.p$i {width:$i%;}}`

This fails on two places: 
the first one is on .p$i that I've found should be .p-$i and I can live with this;
the second one is on the percent sign, If I remove it, it expands perfectly. 

Is there any way to escape the % sign inside a @for or a @def? Is this a bug?

Best regards,
Paulo Melo

**Comment by iflan** [comment]
Design doc is here: go/gss-loops-design

Bugs to the author, please. But we'll take a patch, too. :-)

Ian

**Comment by iflan** [comment]
Sorry, I pointed to the internal docs. I'll export them and send another
link.

Ian

**Comment by iflan** [comment]
Here you go:

https://github.com/google/closure-stylesheets/wiki/@for-loops

Thus, to fix your problem, use `mult(1%, $i)` and you'll get the result as a percent.

**Comment by PauloMelo** [comment]
Many thanks!
