### ISSUE TITLE
backslash nine ( \9 ) is not working

### ISSUE THREAD

**Issue by mxab** [google/closure-stylesheets#9]
Hi,
in the bootstrap css
```
input[type="checkbox"] {
  margin: 4px 0 0;
  margin-top: 1px \9;
  line-height: normal; }
``` 

I think it is a the same issue as described here on google code
https://code.google.com/p/closure-stylesheets/issues/detail?id=20

Any idea how to work around this without modify the source css?

**Comment by iflan** [comment]
The CSS compiler is not designed to support hacks like this. Instead, the
preferred method is to target browsers with different generated stylesheets
using @if (...) { ... }. (We support the star hack for historical reasons.)

Ian

**Comment by mxab** [comment]
Ok, so the only thing I could do to process the source css and replace:
```
margin-top: 1px \9;
```
with 
```
@if (BROWSER_IE9) {
margin-top: 1px;
}
```
and then run the gss once with --define BROWSER_IE9 and once without the flag, I guess?

**Comment by iflan** [comment]
That's the idea, yes. The goal is to have lean stylesheets for each
browser. Perhaps, as older, terrible, browsers die out, we won't even need
that.

Ian

**Comment by mxab** [comment]
cool thanks for the clarification 
I guess also for know I simply kick out all "\9;" lines
