### ISSUE TITLE
Cannot build from source [help wanted]

### ISSUE THREAD

**Issue by iSynth** [google/closure-stylesheets#92]
$ git clone https://code.google.com/p/closure-stylesheets/
$ cd closure-stylesheets
$ mvn compile assembly:single

[INFO] Scanning for projects...

*****

[INFO] 
[INFO] --- maven-assembly-plugin:2.3:single (default-cli) @ closure-stylesheets ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.066s
[INFO] Finished at: Tue Aug 30 15:26:41 MSK 2016
[INFO] Final Memory: 16M/224M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.3:single (default-cli) on project closure-stylesheets: Error reading assemblies: No assembly descriptors found. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by iflan** [comment]
Works for me. What's your Maven version?

```shell
$ mvn -v
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: /Users/flan/Library/apache-maven-3.3.3
Java version: 1.8.0_25, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"
```

**Comment by iSynth** [comment]
@iflan 

$ mvn -v
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.7.0_111, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.19.0-51-generic", arch: "amd64", family:

**Comment by iSynth** [comment]
@iflan 

Updating maven does not help

$ sudo apt-get purge maven maven2 maven3
$ sudo apt-add-repository ppa:andrei-pozolotin/maven3
$ sudo apt-get update
$ sudo apt-get install maven3
$ mvn -v

Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T19:41:47+03:00)
Maven home: /usr/share/maven3
Java version: 1.7.0_111, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.19.0-51-generic", arch: "amd64", family: "unix"

$ mvn compile assembly:single

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15.598 s
[INFO] Finished at: 2016-08-30T16:28:50+03:00
[INFO] Final Memory: 24M/352M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.2-beta-5:single (default-cli) on project closure-stylesheets: Error reading assemblies: No assembly descriptors found. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by iflan** [comment]
You are correct. I have no idea what changed. I'm investigating.

**Comment by mikesamuel** [comment]
Why are you doing `assembly:single` instead of `package` or `verify`?

**Comment by iflan** [comment]
We're trying to get a runnable JAR. I had that working this morning:

```none
$ mvn clean                *[mvn-runnable-jar] 
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Closure Stylesheets 21060712-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ closure-stylesheets ---
[INFO] Deleting /Users/flan/Projects/closure-stylesheets/target
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.647 s
[INFO] Finished at: 2016-08-30T14:06:39+02:00
[INFO] Final Memory: 7M/245M
[INFO] ------------------------------------------------------------------------
[~/Projects/closure-stylesheets]$ mvn compile assembly:single
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Closure Stylesheets 21060712-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The artifact javacc:javacc:jar:4.1 has been relocated to net.java.dev.javacc:javacc:jar:4.1
[INFO] 
[INFO] --- ph-javacc-maven-plugin:2.8.0:javacc (jjc1) @ closure-stylesheets ---
Java Compiler Compiler Version 6.1_2 (Parser Generator)
(type "javacc" with no arguments for help)
Reading from file /Users/flan/Projects/closure-stylesheets/src/com/google/common/css/compiler/ast/GssParserCC.jj . . .
Note: UNICODE_INPUT option is specified. Please make sure you create the parser/lexer using a Reader with the correct character encoding.
File "TokenMgrError.java" does not exist.  Will create one.
File "ParseException.java" does not exist.  Will create one.
File "Token.java" does not exist.  Will create one.
File "CharStream.java" does not exist.  Will create one.
Parser generated successfully.
[INFO] Processed 1 grammar
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ closure-stylesheets ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/flan/Projects/closure-stylesheets/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ closure-stylesheets ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 201 source files to /Users/flan/Projects/closure-stylesheets/target/classes
[INFO] 
[INFO] --- maven-assembly-plugin:2.6:single (default-cli) @ closure-stylesheets ---
[WARNING] While downloading javacc:javacc:4.1
  This artifact has been relocated to net.java.dev.javacc:javacc:4.1.


[INFO] Building jar: /Users/flan/Projects/closure-stylesheets/target/closure-stylesheets-21060712-SNAPSHOT-jar-with-dependencies.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.262 s
[INFO] Finished at: 2016-08-30T14:06:58+02:00
[INFO] Final Memory: 49M/392M
[INFO] ------------------------------------------------------------------------
```

It's possible that I had some changes locally that I managed to blow away.

**Comment by iflan** [comment]
Ah, interesting. My failing run has this:

```none
[INFO] --- maven-assembly-plugin:2.2-beta-5:single (default-cli) @ closure-stylesheets ---
```

while the passing run has this:

```none
[INFO] --- maven-assembly-plugin:2.6:single (default-cli) @ closure-stylesheets ---
```
